version: "3.7"

services: 
  database:
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=nlw5
      - POSTGRES_DB=projeto_nlw
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: nlw5
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on: 
      - database

volumes:
  pgdata:
    driver: local 